package alauncher.cn.measuringinstrument.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import alauncher.cn.measuringinstrument.bean.CodeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CODE_BEAN".
*/
public class CodeBeanDao extends AbstractDao<CodeBean, Long> {

    public static final String TABLENAME = "CODE_BEAN";

    /**
     * Properties of entity CodeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CodeID = new Property(0, long.class, "codeID", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
    }


    public CodeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public CodeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CODE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY NOT NULL ," + // 0: codeID
                "\"NAME\" TEXT);"); // 1: name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CODE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CodeBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodeID());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CodeBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodeID());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public CodeBean readEntity(Cursor cursor, int offset) {
        CodeBean entity = new CodeBean( //
            cursor.getLong(offset + 0), // codeID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CodeBean entity, int offset) {
        entity.setCodeID(cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(CodeBean entity, long rowId) {
        entity.setCodeID(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(CodeBean entity) {
        if(entity != null) {
            return entity.getCodeID();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(CodeBean entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
