package alauncher.cn.measuringinstrument.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import alauncher.cn.measuringinstrument.bean.SetupBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SETUP_BEAN".
*/
public class SetupBeanDao extends AbstractDao<SetupBean, Void> {

    public static final String TABLENAME = "SETUP_BEAN";

    /**
     * Properties of entity SetupBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CodeID = new Property(0, int.class, "codeID", false, "CODE_ID");
        public final static Property Accout = new Property(1, String.class, "accout", false, "ACCOUT");
    }


    public SetupBeanDao(DaoConfig config) {
        super(config);
    }
    
    public SetupBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SETUP_BEAN\" (" + //
                "\"CODE_ID\" INTEGER NOT NULL ," + // 0: codeID
                "\"ACCOUT\" TEXT);"); // 1: accout
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SETUP_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SetupBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodeID());
 
        String accout = entity.getAccout();
        if (accout != null) {
            stmt.bindString(2, accout);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SetupBean entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCodeID());
 
        String accout = entity.getAccout();
        if (accout != null) {
            stmt.bindString(2, accout);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SetupBean readEntity(Cursor cursor, int offset) {
        SetupBean entity = new SetupBean( //
            cursor.getInt(offset + 0), // codeID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // accout
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SetupBean entity, int offset) {
        entity.setCodeID(cursor.getInt(offset + 0));
        entity.setAccout(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SetupBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SetupBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(SetupBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
