package alauncher.cn.measuringinstrument.database.greenDao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import alauncher.cn.measuringinstrument.utils.StringConverter;
import java.util.List;

import alauncher.cn.measuringinstrument.bean.StoreBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STORE_BEAN".
*/
public class StoreBeanDao extends AbstractDao<StoreBean, Long> {

    public static final String TABLENAME = "STORE_BEAN";

    /**
     * Properties of entity StoreBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property StoreMode = new Property(1, int.class, "storeMode", false, "STORE_MODE");
        public final static Property MValue = new Property(2, int.class, "mValue", false, "M_VALUE");
        public final static Property UpLimitValue = new Property(3, String.class, "upLimitValue", false, "UP_LIMIT_VALUE");
        public final static Property LowLimitValue = new Property(4, String.class, "lowLimitValue", false, "LOW_LIMIT_VALUE");
        public final static Property IsScale = new Property(5, String.class, "isScale", false, "IS_SCALE");
        public final static Property Scale = new Property(6, String.class, "scale", false, "SCALE");
        public final static Property Stable = new Property(7, String.class, "stable", false, "STABLE");
        public final static Property DelayTime = new Property(8, int.class, "delayTime", false, "DELAY_TIME");
    }

    private final StringConverter upLimitValueConverter = new StringConverter();
    private final StringConverter lowLimitValueConverter = new StringConverter();
    private final StringConverter isScaleConverter = new StringConverter();
    private final StringConverter scaleConverter = new StringConverter();
    private final StringConverter stableConverter = new StringConverter();

    public StoreBeanDao(DaoConfig config) {
        super(config);
    }
    
    public StoreBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STORE_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"STORE_MODE\" INTEGER NOT NULL ," + // 1: storeMode
                "\"M_VALUE\" INTEGER NOT NULL ," + // 2: mValue
                "\"UP_LIMIT_VALUE\" TEXT," + // 3: upLimitValue
                "\"LOW_LIMIT_VALUE\" TEXT," + // 4: lowLimitValue
                "\"IS_SCALE\" TEXT," + // 5: isScale
                "\"SCALE\" TEXT," + // 6: scale
                "\"STABLE\" TEXT," + // 7: stable
                "\"DELAY_TIME\" INTEGER NOT NULL );"); // 8: delayTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STORE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, StoreBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStoreMode());
        stmt.bindLong(3, entity.getMValue());
 
        List upLimitValue = entity.getUpLimitValue();
        if (upLimitValue != null) {
            stmt.bindString(4, upLimitValueConverter.convertToDatabaseValue(upLimitValue));
        }
 
        List lowLimitValue = entity.getLowLimitValue();
        if (lowLimitValue != null) {
            stmt.bindString(5, lowLimitValueConverter.convertToDatabaseValue(lowLimitValue));
        }
 
        List isScale = entity.getIsScale();
        if (isScale != null) {
            stmt.bindString(6, isScaleConverter.convertToDatabaseValue(isScale));
        }
 
        List scale = entity.getScale();
        if (scale != null) {
            stmt.bindString(7, scaleConverter.convertToDatabaseValue(scale));
        }
 
        List stable = entity.getStable();
        if (stable != null) {
            stmt.bindString(8, stableConverter.convertToDatabaseValue(stable));
        }
        stmt.bindLong(9, entity.getDelayTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, StoreBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getStoreMode());
        stmt.bindLong(3, entity.getMValue());
 
        List upLimitValue = entity.getUpLimitValue();
        if (upLimitValue != null) {
            stmt.bindString(4, upLimitValueConverter.convertToDatabaseValue(upLimitValue));
        }
 
        List lowLimitValue = entity.getLowLimitValue();
        if (lowLimitValue != null) {
            stmt.bindString(5, lowLimitValueConverter.convertToDatabaseValue(lowLimitValue));
        }
 
        List isScale = entity.getIsScale();
        if (isScale != null) {
            stmt.bindString(6, isScaleConverter.convertToDatabaseValue(isScale));
        }
 
        List scale = entity.getScale();
        if (scale != null) {
            stmt.bindString(7, scaleConverter.convertToDatabaseValue(scale));
        }
 
        List stable = entity.getStable();
        if (stable != null) {
            stmt.bindString(8, stableConverter.convertToDatabaseValue(stable));
        }
        stmt.bindLong(9, entity.getDelayTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public StoreBean readEntity(Cursor cursor, int offset) {
        StoreBean entity = new StoreBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // storeMode
            cursor.getInt(offset + 2), // mValue
            cursor.isNull(offset + 3) ? null : upLimitValueConverter.convertToEntityProperty(cursor.getString(offset + 3)), // upLimitValue
            cursor.isNull(offset + 4) ? null : lowLimitValueConverter.convertToEntityProperty(cursor.getString(offset + 4)), // lowLimitValue
            cursor.isNull(offset + 5) ? null : isScaleConverter.convertToEntityProperty(cursor.getString(offset + 5)), // isScale
            cursor.isNull(offset + 6) ? null : scaleConverter.convertToEntityProperty(cursor.getString(offset + 6)), // scale
            cursor.isNull(offset + 7) ? null : stableConverter.convertToEntityProperty(cursor.getString(offset + 7)), // stable
            cursor.getInt(offset + 8) // delayTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, StoreBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setStoreMode(cursor.getInt(offset + 1));
        entity.setMValue(cursor.getInt(offset + 2));
        entity.setUpLimitValue(cursor.isNull(offset + 3) ? null : upLimitValueConverter.convertToEntityProperty(cursor.getString(offset + 3)));
        entity.setLowLimitValue(cursor.isNull(offset + 4) ? null : lowLimitValueConverter.convertToEntityProperty(cursor.getString(offset + 4)));
        entity.setIsScale(cursor.isNull(offset + 5) ? null : isScaleConverter.convertToEntityProperty(cursor.getString(offset + 5)));
        entity.setScale(cursor.isNull(offset + 6) ? null : scaleConverter.convertToEntityProperty(cursor.getString(offset + 6)));
        entity.setStable(cursor.isNull(offset + 7) ? null : stableConverter.convertToEntityProperty(cursor.getString(offset + 7)));
        entity.setDelayTime(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(StoreBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(StoreBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(StoreBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
